[project]
name = "torch-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.14.0",
    "bs4>=0.0.2",
    "datasets>=5.0.1",
    "diffusers>=0.39.0",
    "evaluate>=0.4.6",
    "ipywidgets>=8.1.8",
    "kagglehub>=1.0.2",
    "langchain>=1.3.15",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-openai>=1.5.0",
    "langchain-postgres>=0.0.17",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.2.11",
    "matplotlib>=3.11.0",
    "numpy>=2.4.4",
    "pypdf>=6.16.0",
    "tokenizers>=0.22.2",
    "torch>=2.13.0",
    "torchsummary>=1.5.1",
    "torchvision>=0.28.0",
    "transformers>=5.14.1",
]

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupytext>=1.19.5",
]
